[tool.poetry]
name = "goit-web-hw-04"
version = "0.1.0"
description = "modul4"
authors = ["juliia <poshtaklon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
